library(readr)

datos1 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-AR-A1AR/dataset.tsv")
datos2 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-A2-A1G1/dataset_1.tsv")
datos3 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-A1-A0SI/dataset_2.tsv")
datos4 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-A7-A2KD/dataset_3.tsv")
datos5 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-A7-A26F/dataset_4.tsv")
datos6 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-A7-A26G/dataset_5.tsv")
datos7 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-A7-A26I/dataset_6.tsv")
datos9 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-AC-A3OD/dataset_8.tsv")
datos10 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-AC-A23C/dataset_9.tsv")
datos11 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-AR-A2LR/dataset_10.tsv")
datos13 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-AR-A24K/dataset_12.tsv")
datos14 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-AR-A24P/dataset_13.tsv")
datos15 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-AR-A24S/dataset_14.tsv")
datos16 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-AR-A24T/dataset_15.tsv")
datos17 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-AR-A251/dataset_16.tsv")
datos18 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-AR-A254/dataset_17.tsv")
datos19 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-AR-A256/dataset_18.tsv")
datos20 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-B6-A1KF/dataset_19.tsv")
datos21 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-B6-A1KN/dataset_20.tsv")
datos22 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-BH-A1EY/dataset_21.tsv")
datos23 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-BH-A1F0/dataset_22.tsv")
datos24 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-BH-A1F2/dataset_23.tsv")
datos25 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-BH-A1F6/dataset_24.tsv")
datos27 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-BH-A1FD/dataset_26.tsv")
datos28 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-BH-A1FE/dataset_27.tsv")
datos29 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-BH-A1FN/dataset_28.tsv")
datos30 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-BH-A1FU/dataset_29.tsv")
datos31 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-BH-A202/dataset_30.tsv")
datos32 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-BH-A208/dataset_31.tsv")
datos33 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-C8-A1HG/dataset_32.tsv")
datos34 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-C8-A1HJ/dataset_33.tsv")
datos35 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-C8-A1HK/dataset_34.tsv")
datos36 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-C8-A1HM/dataset_35.tsv")
datos37 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-C8-A26V/dataset_36.tsv")
datos38 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-C8-A26W/dataset_37.tsv")
datos39 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-C8-A26X/dataset_38.tsv")
datos40 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-C8-A27A/dataset_39.tsv")
datos41 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-C8-A27B/dataset_40.tsv")
datos42 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-C8-A275/dataset_41.tsv")
datos43 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-C8-A278/dataset_42.tsv")
datos44 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-D8-A1J9/dataset_43.tsv")
datos45 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-D8-A1JF/dataset_44.tsv")
datos46 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-D8-A1JG/dataset_45.tsv")
datos47 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-D8-A1JJ/dataset_46.tsv")
datos48 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-D8-A1JK/dataset_47.tsv")
datos49 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-D8-A1JL/dataset_48.tsv")
datos50 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-D8-A1JM/dataset_49.tsv")
datos51 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-D8-A1X5/dataset_50.tsv")
datos52 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-D8-A1XA/dataset_51.tsv")
datos53 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-D8-A1XJ/dataset_52.tsv")
datos54 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-D8-A1XL/dataset_53.tsv")
datos55 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-D8-A1XQ/dataset_54.tsv")
datos56 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-D8-A1XT/dataset_55.tsv")
datos57 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-D8-A1XW/dataset_56.tsv")
datos58 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-D8-A1XZ/dataset_57.tsv")
datos59 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-D8-A1Y3/dataset_58.tsv")
datos60 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-D8-A27F/dataset_59.tsv")
datos61 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-D8-A27M/dataset_60.tsv")
datos62 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-D8-A27N/dataset_61.tsv")
datos63 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-E2-A1II/dataset_62.tsv")
datos64 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-E2-A1IN/dataset_63.tsv")
datos65 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-E2-A1IO/dataset_64.tsv")
datos66 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-E2-A1L7/dataset_65.tsv")
datos67 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-E2-A1LE/dataset_66.tsv")
datos68 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-E2-A1LG/dataset_67.tsv")
datos69 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-E2-A1LH/dataset_68.tsv")
datos70 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-E2-A1LK/dataset_69.tsv")
datos71 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-E2-A1LS/dataset_70.tsv")
datos72<- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-E2-A2P5/dataset_71.tsv")
datos73 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-E2-A14N/dataset_72.tsv")
datos74 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-E9-A1N5/dataset_73.tsv")
datos75 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-E9-A1N8/dataset_74.tsv")
datos76<- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-E9-A1N9/dataset_75.tsv")
datos77 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-E9-A1ND/dataset_76.tsv")
datos78 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-E9-A1NF/dataset_77.tsv")
datos79<- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-E9-A1RB/dataset_78.tsv")
datos80 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-E9-A1RH/dataset_79.tsv")
datos81 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-E9-A244/dataset_80.tsv")
datos82 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-E9-A248/dataset_81.tsv")
datos83 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-EW-A1OY/dataset_82.tsv")
datos84 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-EW-A1OZ/dataset_83.tsv")
datos86 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-EW-A1PA/dataset_85.tsv")
datos87 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-EW-A1PC/dataset_86.tsv")
datos88 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-EW-A1PH/dataset_87.tsv")
datos89 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-EW-A2FR/dataset_88.tsv")
datos90 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-EW-A3U0/dataset_89.tsv")
datos91 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-GI-A2C9/dataset_90.tsv")
datos92 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-GM-A2DB/dataset_91.tsv")
datos93 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-GM-A2DD/dataset_92.tsv")
datos94 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-GM-A2DF/dataset_93.tsv")
datos95 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-GM-A2DH/dataset_94.tsv")
datos96 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-GM-A2DI/dataset_95.tsv")
datos97 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-GM-A2DL/dataset_96.tsv")
datos98 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-GM-A3XL/dataset_97.tsv")
datos99 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-A2-A3XS/dataset_98.tsv")
datos100 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-A2-A3XT/dataset_99.tsv")
datos101 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-A2-A3XV/dataset_100.tsv")
datos102 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-A2-A3XX/dataset_101.tsv")
datos103 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-A2-A3XY/dataset_102.tsv")
datos104 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-A2-A3Y0/dataset_103.tsv")
datos106 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-B6-A402/dataset_105.tsv")
datos107 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-B6-A401/dataset_106.tsv")
datos108 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-B6-A409/dataset_107.tsv")
#datos109 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-B6-A3ZX/dataset_108.tsv")
datos110 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-B6-A400/dataset_109.tsv")
datos111 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-JL-A3YW/dataset_110.tsv")
datos113 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-A2-A4S3/dataset_112.tsv")
datos114 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-A7-A4SA/dataset_113.tsv")
datos115 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-A7-A4SD/dataset_114.tsv")
datos116 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-A7-A4SE/dataset_115.tsv")
datos118 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-A7-A5ZV/dataset_117.tsv")
datos119 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-A8-A09X/dataset_118.tsv")
datos120 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-Z7-A8R6/dataset_119.tsv")
datos121 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-BH-A18V/dataset_120.tsv")
datos122 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-E2-A15M/dataset_121.tsv")
datos123 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-AR-A2LH/dataset_123.tsv")
datos124 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-HN-A2NL/dataset_124.tsv")
datos125 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-E9-A6HE/dataset_125.tsv")
datos126 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-PE-A5DE/dataset_122.tsv")
datos127 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-B6-A0IE/dataset_126.tsv")
datos128 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/MB-0102/dataset_127.tsv")
datos129 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/MB-0344/dataset_128.tsv")
datos130 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/MB-0582/dataset_129.tsv")
datos131 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/MB-0653/dataset_130.tsv")
datos132 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/MB-2854/dataset_131.tsv")
datos133 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/MB-2900/dataset_132.tsv")
datos134 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/MB-4005/dataset_133.tsv")
datos135 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/MB-4033/dataset_134.tsv")
datos136 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/MB-4667/dataset_135.tsv")
datos137 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/MB-4860/dataset_136.tsv")
datos138 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/MB-5298/dataset_137.tsv")
datos139 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/MB-5299/dataset_138.tsv")
datos140 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/MB-5313/dataset_139.tsv")
datos141 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/MB-5327/dataset_140.tsv")
datos142 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/MB-5329/dataset_141.tsv")
datos143 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/MB-5390/dataset_142.tsv")
datos144 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/MB-5392/dataset_143.tsv")
datos145 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/MB-5493/dataset_144.tsv")
datos146 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/MB-5577/dataset_145.tsv")
datos147 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/MB-5593/dataset_146.tsv")
datos148 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/MB-6007/dataset_147.tsv")
datos149 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/MB-6358/dataset_148.tsv")
datos150 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/MB-7054/dataset_149.tsv")
datos151 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/MB-7273/dataset_150.tsv")
datos152 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/MB-7283/dataset_151.tsv")
datos153 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/MTS-T0066/dataset_152.tsv")
datos154 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/MTS-T0094/dataset_153.tsv")
datos155 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/MTS-T0183/dataset_154.tsv")
datos156 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/MTS-T0194/dataset_155.tsv")
datos157 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/MTS-T0230/dataset_156.tsv")
datos158 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/MTS-T0245/dataset_157.tsv")
datos159 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/MTS-T0685/dataset_158.tsv")
datos160 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/MTS-T0701/dataset_159.tsv")
datos161 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/MTS-T2085/dataset_160.tsv")
datos162 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/MTS-T2127/dataset_161.tsv")
datos187 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/P-0002591/dataset_186.tsv")
datos188 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/P004/dataset_187.tsv")
datos189 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/P019/dataset_188.tsv")
datos190 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/P040/dataset_189.tsv")
datos191 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-B6-A0WX/dataset_196.tsv")
datos192 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-BH-A0C3/dataset_197.tsv")
datos193 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-AN-A0AJ/dataset_198.tsv")
datos194 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-AQ-A04H/dataset_199.tsv")
datos195 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-C8-A130/dataset_200.tsv")
datos196 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-E2-A14Y/dataset_201.tsv")
datos197 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-BH-A0E0/dataset_202.tsv")
datos198 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-E2-A155/dataset_203.tsv")
datos199 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-B6-A0RT/dataset_204.tsv")
datos200 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-LL-A5YP/dataset_205.tsv")
datos201 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-BH-A203/dataset_206.tsv")
datos202 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-BH-A1FH/dataset_207.tsv")
datos203 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-A8-A097/dataset_208.tsv")
datos204 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-BH-A0B0/dataset_209.tsv")
datos205 <- read_tsv("/Users/francinazuliani/Desktop/TF/Database/TCGA-BH-A0AW/dataset_210.tsv")



datos_combinados <- rbind(datos1, datos2, datos3, datos4, datos5, datos6, datos7, datos9, datos10, 
                          datos11, datos13, datos14, datos15, datos16, datos17, datos18, datos19, 
                          datos20, datos21, datos22, datos23, datos24, datos25, datos27, datos28,
                          datos29, datos30, datos31, datos32, datos33, datos34, datos35, datos36, datos37,
                          datos38, datos39, datos40, datos41, datos42, datos43, datos44, datos45, datos46,
                          datos47, datos48, datos49, datos50, datos51, datos52, datos53, datos54, datos55, 
                          datos56, datos57, datos58, datos59, datos60, datos61, datos62, datos63, datos64, 
                          datos65, datos66, datos67, datos68, datos69, datos70, datos71, datos72, datos73, 
                          datos74, datos75, datos76, datos77, datos78, datos79, datos80, datos81, datos82, 
                          datos83, datos84, datos86, datos87, datos88, datos89, datos90, datos91, 
                          datos92, datos93, datos94, datos95, datos96, datos97, datos98, datos99, datos100, 
                          datos101, datos102, datos103, datos104, datos106, datos107, datos108, 
                          datos110, datos111, datos113, datos114, datos115, datos116, 
                          datos118, datos119, datos120, datos121, datos122, datos123, datos124, 
                          datos125, datos126, datos127, datos128, datos129, datos130, datos131, datos132, 
                          datos133, datos134, datos135, datos136, datos137, datos138, datos139, datos140,
                          datos141, datos142, datos143, datos144, datos145, datos146, datos147, datos148,
                          datos149, datos150, datos151, datos152, datos153, datos154, datos155, datos156,
                          datos157, datos158, datos159, datos160, datos161, datos162, 
                          datos187, datos188, datos189, datos190, datos191, datos192,
                          datos193, datos194, datos195, datos196, datos197, datos198, datos199, datos200, 
                          datos201, datos202, datos203, datos204, datos205)

View(datos_combinados)

ncol(datos205)

setwd("/Users/francinazuliani/Desktop/TF/Database/")
write.table(datos_combinados, file = "datos_combinados.tsv", sep = "\t", quote = FALSE, row.names = FALSE)

#------------------FILTRO POR TIPOS QUE NECESITO----
df <- subset(datos_combinados, `Neoplasm Histologic Type Name` == 'Infiltrating Lobular Carcinoma' | `Neoplasm Histologic Type Name` == 'Infiltrating Ductal Carcinoma')
View(df)
setwd("/Users/francinazuliani/Desktop/TF/Database/")
write.table(df, file = "df.tsv", sep = "\t", quote = FALSE, row.names = FALSE)

